import { Vollkorn } from "next/font/google";
import "./globals.css";

const vollkorn = Vollkorn({ subsets: ["latin"] , weight:'600' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={vollkorn.className}>{children}</body>
    </html>
  );
}
